<template>
  <section>
    <div>
      <v-row>
        <v-col
            md="6"
            cols="12"
            sm="12">
            <h3>
              NUESTROS VALORES:
            </h3>
            <v-row>
              <v-col
                cols="1">
                <br>
                <v-icon>
                  mdi-star
                </v-icon>
              </v-col>
              <v-col
                cols="11">
                  <v-row>
                    <v-col
                      cols="12">
                      <h3>
                        EXCELENCIA
                      </h3>
                    </v-col>
                  </v-row>
                  <v-row>
                    <v-col
                      cols="12">
                      Para nosotros un trabajo debe realizarse con la mejor actitud y con la materia de más alta calidad para mantener los altos estándares que exige tanto el mercado como nuestros clientes.
                    </v-col>
                  </v-row>
              </v-col>
            </v-row>
          <v-row>
            <v-col
                cols="1">
              <br>
              <v-icon>
                mdi-leaf
              </v-icon>
            </v-col>
            <v-col
                cols="11">
              <v-row>
                <v-col
                    cols="12">
                  <h3>
                    HONESTIDAD
                  </h3>
                </v-col>
              </v-row>
              <v-row>
                <v-col
                    cols="12">
                    Trabajamos con el propósito de hacer nuestra labor de la mejor manera posible para crear vínculos de confianza con nuestros clientes.
                </v-col>
              </v-row>
            </v-col>
          </v-row>
          <v-row>
            <v-col
                cols="1">
              <br>
              <v-icon>
                mdi-lightbulb-outline
              </v-icon>
            </v-col>
            <v-col
                cols="11">
              <v-row>
                <v-col
                    cols="12">
                  <h3>
                    RESPETO
                  </h3>
                </v-col>
              </v-row>
              <v-row>
                <v-col
                    cols="12">
                    Mantenemos una línea de confianza basada en la educación y buen trato tanto para nuestros colaboradores como para nuestros clientes.
                </v-col>
              </v-row>
            </v-col>
          </v-row>
          <v-row>
            <v-col
                cols="1">
              <br>
              <v-icon>
                mdi-layers-triple-outline
              </v-icon>
            </v-col>
            <v-col
                cols="11">
              <v-row>
                <v-col
                    cols="12">
                  <h3>
                    EXCELENCIA
                  </h3>
                </v-col>
              </v-row>
              <v-row>
                <v-col
                    cols="12">
                  Para nosotros un trabajo debe realizarse con la mejor actitud y con la materia de más alta calidad para mantener los altos estándares que exige tanto el mercado como nuestros clientes.
                </v-col>
              </v-row>
            </v-col>
          </v-row>
        </v-col>
        <v-col
            md="6"
            cols="12"
            sm="12">
          <v-row>
            <v-col
              cols="12">
              <h2>
                ING. LUIS RAMOS
              </h2>
              <h4>
                GERENTE GENERAL
              </h4>
              <h3>
                TEL. 5018 - 8659
              </h3>
              <h3>LUIS.RAMOS@trasisa.com</h3>
            </v-col>
          </v-row>
          <br>
          <br>
          <br>
          <v-row>
            <v-col
              cols="12">
              <h2>
                INFORMACIÓN
              </h2>
            </v-col>
          </v-row>
          <v-row>
            <v-col
                cols="7">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-domain
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    25 Avenida 5-30 zona 18, Ofibodegas la Módena B-1
                  </p>
                </v-col>
              </v-row>
            </v-col>
            <v-col
                cols="5">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-phone
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    2256 4430
                  </p>
                </v-col>
              </v-row>
            </v-col>
          </v-row>
          <v-row>
            <v-col
                cols="7">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-pencil
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    informacion@trasisa.com.gt
                  </p>
                </v-col>
              </v-row>
            </v-col>
            <v-col
                cols="5">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-facebook
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    trasisa
                  </p>
                </v-col>
              </v-row>
            </v-col>
          </v-row>
          <v-row>
            <v-col
                cols="7">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-youtube
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    trasisa
                  </p>
                </v-col>
              </v-row>
            </v-col>
            <v-col
                cols="5">
              <v-row>
                <v-col
                    cols="2">
                  <v-icon>
                    mdi-linkedin
                  </v-icon>
                </v-col>
                <v-col
                    cols="10">
                  <p>
                    trasisa
                  </p>
                </v-col>
              </v-row>
            </v-col>
          </v-row>
        </v-col>
      </v-row>
    </div>
  </section>
</template>

<script>
export default {
  name: 'About'
}
</script>